development:
  adapter: postgresql
  encoding: unicode
  database: post_dev
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: post_test
  pool: 5
  username:
  password: